name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip openjdk-11-jdk
        pip install --upgrade pip
        pip install cython buildozer

    - name: Accept Android SDK Licenses & Install SDK
      run: |
        mkdir -p $HOME/android-sdk
        cd $HOME/android-sdk
        curl -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip sdk.zip
        mv cmdline-tools latest
        mkdir -p cmdline-tools/latest
        mv latest cmdline-tools/
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
        yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
        yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;34.0.0"

    - name: Build APK with Buildozer
      run: |
        export ANDROIDSDK=$HOME/android-sdk
        export PATH=$ANDROIDSDK/cmdline-tools/latest/bin:$PATH
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: safespot-debug-apk
        path: bin/*.apk
