name: Build APK

on:
  push:
    branches: [main]

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Buildozer & Cython
      run: |
        pip install --upgrade pip
        pip install cython buildozer

    - name: Set up Android SDK & Build Tools
      uses: android/setup-android@v2
      with:
        sdk: '33'
        build-tools: '34.0.0'
        ndk: none
        components: android-33,build-tools;34.0.0,platform-tools

    - name: Build APK with Buildozer
      run: |
        export ANDROIDSDK="$ANDROID_SDK_ROOT"           # setup-android exports this
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: safespot-debug-apk
        path: bin/*.apk
