name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install cython buildozer

    - name: Set up Android SDK manually
      run: |
        mkdir -p $HOME/android-sdk
        cd $HOME/android-sdk
        curl -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip sdk.zip -d cmdline-tools
        mv cmdline-tools cmdline-tools-temp
        mkdir cmdline-tools
        mv cmdline-tools-temp cmdline-tools/latest
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
        yes | sdkmanager --licenses
        yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;34.0.0"

    - name: Build APK with Buildozer
      run: |
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export ANDROIDSDK=$HOME/android-sdk
        export PATH=$ANDROID_SDK_ROOT/build-tools/34.0.0:$ANDROID_SDK_ROOT/platform-tools:$PATH
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: safespot-debug-apk
        path: bin/*.apk
